apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::655931526155:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-16MNK1CQVI6BK
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::655931526155:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-30T22:53:24Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-05-30T22:53:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1542"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 874d0b36-d1c4-4fbe-9ee3-849605b83c10
